app:
  scheduler:
    interval: 10s

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packages-to-scan: edu.java.bot, edu.java.scrapper
  api-docs:
    path: /v3/api-docs

