app:
  scheduler:
    interval: 10s
  http-client:
    retry:
      max-attempts: 3
      backoff-type: exponential # constant, linear, exponential
      backoff-delay: 500 # ms
      retry-codes: [500, 502, 503, 504]
  rate-limit:
    capacity: 10
    refill-tokens: 10
    refill-duration: 1m

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packages-to-scan: edu.java.bot, edu.java.scrapper
  api-docs:
    path: /v3/api-docs

scrapper:
  base-url: http://localhost:8080
bot:
  base-url: http://localhost:8090
  kafka-bootstrap-servers: localhost:9092
  scrapper-topic:
    name: link-updates
    dlq-name: link-updates_dlq
  use-queue: true

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}



