app:
  telegram-token: 7717771695:AAHu1jNw11IFbyEtK9qLFZ7WJAWSzCQiUqE
  kafka-bootstrap-servers: localhost:9092
  scrapper-topic:
    name: link-updates
    dlq-name: link-updates_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packages-to-scan: edu.java.bot, edu.java.scrapper
  api-docs:
    path: /v3/api-docs

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
