app:
  telegram-token: 7717771695:AAHu1jNw11IFbyEtK9qLFZ7WJAWSzCQiUqE

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packages-to-scan: edu.java.bot, edu.java.scrapper
  api-docs:
    path: /v3/api-docs
