name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn package
    
    - name: Build Docker images
      run: |
        docker build -f bot/Dockerfile -t bot .
        docker build -f scrapper/Dockerfile -t scrapper .
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag and push bot image
      run: |
        docker tag bot ghcr.io/alexanderstepanov05/link-tracker-bot:${{ github.sha }}
        docker tag bot ghcr.io/alexanderstepanov05/link-tracker-bot:latest
        docker push ghcr.io/alexanderstepanov05/link-tracker-bot:${{ github.sha }}
        docker push ghcr.io/alexanderstepanov05/link-tracker-bot:latest
    
    - name: Tag and push scrapper image
      run: |
        docker tag scrapper ghcr.io/alexanderstepanov05/link-tracker-bot-scrapper:${{ github.sha }}
        docker tag scrapper ghcr.io/alexanderstepanov05/link-tracker-bot-scrapper:latest
        docker push ghcr.io/alexanderstepanov05/link-tracker-bot-scrapper:${{ github.sha }}
        docker push ghcr.io/alexanderstepanov05/link-tracker-bot-scrapper:latest 